---
- name: FIrst Playbook
  hosts: all
  become: yes
  tasks:
  - name: my first server
    apt:
     name: nginx
     state: latest

  - name: my second server
    apt:
     name: tree
     state: latest
  
  - name: my third server
    apt:
     name: apache2
     state: latest
...
