---
- name: Example playbook with loop kind of work
  hosts: all
  become: yes
  tasks:
    - name: Add list of users in my nodes
      user: name = "{{}}" state = present
      with_items:
        - jarvis
        - spider
        - peter
        - dr_banner
...